name: Build & Push Container Images & Push Helm Chart

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-push-bump:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/akmaslov-dev/csi-rclone
          tags: |
            # Produces semver tags (0.4.3, 0.4, 0) when pushing v0.4.3
            # And a 'branch' tag for master pushes
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{raw}}
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Publish Helm chart in GitHub Pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm OCI
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=$(yq e '.version' charts/csi-rclone/Chart.yaml)
          
          mkdir -p helm-release
          helm package charts/csi-rclone/ -d helm-release

          helm push helm-release/csi-rclone-${VERSION}.tgz oci://ghcr.io/akmaslov-dev/charts